### ISSUE TITLE
Uhm... Whoa...

### ISSUE THREAD

**Issue by mamarilmanson** [xlgames-inc/XLE#6]
What's the dev status of this engine??? :D

I was blown off by the image at the fore front of this github repo... :D

**Comment by djewsbury** [comment]
Hi Mamaril,

Thanks for stopping by. XLE is still very much a work in progress. There still a lot of work to do and a lot of features to add. But, working hard and adding new things all the time.

My hope is that many major missing features will come from integrating technologies from other sources (both open source and closed source). XLE already leverages a huge list of existing open-source libraries. Because XLE is truly open source, it should only be necessary to write new code when the existing solutions are not quite right, or not of a sufficient quality. Therefore, most of the code in XLE is focused on areas where it feels like existing solutions don't cover well.

I'm glad you like the screenshots! I don't actually have a lot of art resources to take screenshots of. And we only have limited time for that kind of thing. So it's hard to show the full power of the engine. It takes more than just good technology to take a great screenshot -- it takes great art, scene composition skills, and lots of time and effort.

But I'm feeling more and more confident about the rendering lately. Of course the goal is to target a very up-to-date high-end feature set. That means the kinds of rendering features previous only seen in closed source (and very expensive!) engines.

How would the engine go in a shoot-out against current triple-A PS4 type titles? Well, it's hard to say. There are still many features I want to get in there. But I feel confident we're on the right track. And I feel confident that the current features are of the right kind of quality.

I want to open the door for projects of all sizes to get access to that kind of quality -- on the terms that they want.

Cheers!

**Comment by djewsbury** [comment]
Oh, btw... there are some more screenshots on the development blog:
http://xlgames-inc.github.io/posts/first/

**Comment by mamarilmanson** [comment]
On that note... I see you (or an image of another person) in a podium... then receiving a warm applause after that wonderful presidential speech haha

I was actually searching github of the game engines with most recent update and stumbled upon this one... and was "what? open source? this render looks beautiful! and a ui! wait what???"

but... one thing I really want to mention... a pattern across almost all 3d open source engines... the quality... or worse, even the presence of a fully customizable, functional, fully featured GUI... that's a pattern I'm noticing... they mostly rely on community built or default GUI which is the complete negative of the above... so I hope this won't be the same... if it's this gorgeous I hope the GUI is like an engine of it's own...(I hope you got what I said) :D

**Comment by djewsbury** [comment]
When you say "GUI" do you mean the in-game GUI, or the GUI for the engine tools?

If you mean in-game GUI element, I expect XLE will mostly be used with other middleware for this. There are some good packages out there... "Coherent UI" is an example; but there others (such as maybe http://uiink.com/). 

If you're talking about the engine tools -- well, I come from a background of making in-house engines for game studios. And in that kind of environment, our goal in making tools is usually to maximum the flexible and extensibility of the tools. Often when we start a new game project, we might have an idea about the game design, but we don't really know how it will change over the course of the project.

That means we have to expect and plan for changes along the way... And sometimes that means we have to prioritize flexibility over user friendliness. So, for example, using built-in GUI elements is often best because if something changes, you haven't wasted a lot of time on something that is no longer needed. Also, often experienced artists and design prefer power and features over user-friendliness. That may be part of the reason for the pattern you're seeing...?

There are some engines out there that allow game developers to make games with very little programming skill. I should mention that that kinda isn't what XLE is. XLE is primarily intended for experienced programmers; people who want to extend and expand upon XLE. In that sense, XLE is like a starting place for creating a custom engine tailored for a specific game.

So, now, after saying all that.... I've been using a lot of code from a library called "ATF." This was developed by Sony World Wide Studios; and actually it's pretty neat. Much of core XLE tools behaviour is derived from that library.

Sony seem to be using ATF internally for many years. It's designed well, and it fits perfectly with the priorities I mentioned above... It's extensible, it's flexible. It's easy to add features or experiment with new ideas. And it's intelligently designed.

I'm very happy with ATF as GUI/tools solution. I think it fits well within the spirit of XLE, and it's a great sign that open-source will being to play a bigger and bigger role in serious game development in the future.

ATF has been used in top game projects (like Naughty Dog's Uncharted series). Maybe there's an argument to say that if it's good enough to be used as Naughty Dog, then it should be good enough for anyone (well, at least anyone who wants to work in the same way as that studio).

At first, the GUI stuff in XLE just looks like plain windows... But there is a cool skinning feature in ATF! It's limited to changing the colors and fonts of things -- but I've being playing with it, and it often works very well.

So, this answer may not be what you were hoping for... But I hope it makes my thinking a little bit clear. It may be that one day XLE will have some super-svelte, super-custom tool GUI... But it's hard to see it as a big priority at this stage in the project.

**Comment by DGMurdockIII** [comment]
hey the lead dev posted on your post http://www.gritengine.com/game-engine-forum/viewtopic.php?f=2&t=1812&sid=b504ba167047f2028acd83b1ea1de40b

**Comment by DGMurdockIII** [comment]
left another post for u

**Comment by DGMurdockIII** [comment]
at http://www.gritengine.com/game-engine-forum/viewtopic.php?f=2&t=1812&sid=b504ba167047f2028acd83b1ea1de40b
